package session

import (
	"bufio"
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"
)

var (
	ErrNotFound = errors.New("session not found")
	// ErrArchived rejects writes to an archived session. Archived sessions
	// are read-only: their directory has been moved under Archive/ and no
	// new events may be appended.
	ErrArchived = errors.New("session is archived")
	// ErrSessionActive rejects archiving a session that still has active
	// work: a running or starting provider, an open turn, or a pending
	// approval.
	ErrSessionActive = errors.New("session has active work and cannot be archived")
	// ErrInvalidID rejects session identifiers that are not safe store
	// directory names.
	ErrInvalidID = errors.New("invalid session id")
	// ErrArchiveConflict reports that the archive target already exists.
	ErrArchiveConflict = errors.New("archive target already exists")
	// ErrEventCursorAhead reports a cursor that is newer than the durable
	// head of the requested session. Accepting it would silently skip future
	// events until the store caught up to an unrelated cursor.
	ErrEventCursorAhead = errors.New("event cursor is ahead of durable log")
)

// ArchiveDirName is the subdirectory of the session store that holds
// archived sessions. It never contains a live session and is never scanned
// as one.
const ArchiveDirName = "Archive"

const (
	DefaultEventPageSize = 500
	MaxEventPageSize     = 1000
	subscriptionBuffer   = 256
	// maxMergedDeltaEventBytes caps the accumulated payload of one merged
	// delta event. See mergeableDeltaEvent for why the cap exists.
	maxMergedDeltaEventBytes = 32 << 10
)

var sessionIDPattern = regexp.MustCompile(`^ses_[a-z0-9]+$`)

// validSessionID reports whether id is a safe store directory name. Session
// IDs are generated by NewID, so anything else (path separators, dots,
// traversal attempts) is rejected.
func validSessionID(id string) bool {
	return sessionIDPattern.MatchString(id)
}

type sessionState struct {
	mu      sync.Mutex
	session Session
	events  []Event
	// archived reports whether the session directory lives under Archive/.
	// It is the in-memory record of the physical location, which is the
	// authoritative archive signal.
	archived bool
}

type Store struct {
	root string

	mu          sync.RWMutex
	sessions    map[string]*sessionState
	subscribers map[string]map[*Subscription]struct{}
}

// Subscription is a best-effort notification queue layered over the durable
// event log. Overflow is terminal: callers must end the live connection and
// resume from their last processed durable cursor instead of consuming a
// queue that is known to contain a gap.
type Subscription struct {
	events   chan Event
	overflow chan struct{}
	cancel   func()
	once     sync.Once
}

func (s *Subscription) Events() <-chan Event {
	return s.events
}

func (s *Subscription) Overflow() <-chan struct{} {
	return s.overflow
}

func (s *Subscription) Overflowed() bool {
	select {
	case <-s.overflow:
		return true
	default:
		return false
	}
}

func (s *Subscription) Cancel() {
	s.once.Do(s.cancel)
}

func Open(root string) (*Store, error) {
	if err := os.MkdirAll(root, 0o700); err != nil {
		return nil, fmt.Errorf("create session store: %w", err)
	}
	archiveRoot := filepath.Join(root, ArchiveDirName)
	if err := os.MkdirAll(archiveRoot, 0o700); err != nil {
		return nil, fmt.Errorf("create session archive: %w", err)
	}
	store := &Store{
		root:        root,
		sessions:    make(map[string]*sessionState),
		subscribers: make(map[string]map[*Subscription]struct{}),
	}
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, fmt.Errorf("read session store: %w", err)
	}
	for _, entry := range entries {
		if !entry.IsDir() || !strings.HasPrefix(entry.Name(), "ses_") {
			// Archive itself and any unrelated entry are never sessions.
			continue
		}
		state, err := store.loadSession(filepath.Join(root, entry.Name()), entry.Name())
		if err != nil {
			return nil, fmt.Errorf("load %s: %w", entry.Name(), err)
		}
		if state.session.State == StateArchived {
			// The archived event was appended but the daemon stopped before
			// moving the directory. Complete the move so the physical
			// location matches the event log again.
			if err := os.Rename(filepath.Join(root, entry.Name()), filepath.Join(archiveRoot, entry.Name())); err == nil {
				state.archived = true
				syncDir(archiveRoot)
				syncDir(root)
			}
		}
		store.sessions[entry.Name()] = state
	}
	archivedEntries, err := os.ReadDir(archiveRoot)
	if err != nil {
		return nil, fmt.Errorf("read session archive: %w", err)
	}
	for _, entry := range archivedEntries {
		if !entry.IsDir() || !strings.HasPrefix(entry.Name(), "ses_") {
			continue
		}
		if existing, exists := store.sessions[entry.Name()]; exists {
			if existing.archived {
				// Moved here by the interrupted-archive recovery above.
				continue
			}
			return nil, fmt.Errorf("session %s exists in both the store and the archive", entry.Name())
		}
		state, err := store.loadSession(filepath.Join(archiveRoot, entry.Name()), entry.Name())
		if err != nil {
			return nil, fmt.Errorf("load archived %s: %w", entry.Name(), err)
		}
		// The physical location is authoritative: a session under Archive/
		// is archived even if its event log predates the archived event.
		state.session.State = StateArchived
		state.archived = true
		store.sessions[entry.Name()] = state
	}
	return store, nil
}

func (s *Store) Root() string {
	return s.root
}

// ArchiveRoot returns the directory that holds archived sessions.
func (s *Store) ArchiveRoot() string {
	return s.archiveRoot()
}

func (s *Store) archiveRoot() string {
	return filepath.Join(s.root, ArchiveDirName)
}

func (s *Store) Create(input CreateInput) (Session, error) {
	if err := ValidateLaunchEnvironment(input.LaunchEnvironment); err != nil {
		return Session{}, err
	}
	now := time.Now().UTC()
	id, err := NewID("ses")
	if err != nil {
		return Session{}, err
	}
	if input.Title == "" {
		input.Title = "New Session"
	}
	value := Session{
		ID:                id,
		Title:             input.Title,
		Cwd:               input.Cwd,
		AgentName:         input.AgentName,
		Source:            cloneSource(input.Source),
		LaunchEnvironment: cloneEnvironment(input.LaunchEnvironment),
		State:             StateReady,
		CreatedAt:         now,
		UpdatedAt:         now,
	}
	state := &sessionState{session: value}
	dir := s.sessionDir(id)
	if err := os.Mkdir(dir, 0o700); err != nil {
		return Session{}, fmt.Errorf("create session directory: %w", err)
	}

	s.mu.Lock()
	s.sessions[id] = state
	s.mu.Unlock()

	data, err := json.Marshal(value)
	if err != nil {
		s.removeSession(id)
		_ = os.RemoveAll(dir)
		return Session{}, err
	}
	if _, err := s.Append(id, "session.created", "", data); err != nil {
		s.removeSession(id)
		_ = os.RemoveAll(dir)
		return Session{}, err
	}
	return s.Get(id)
}

func (s *Store) Get(id string) (Session, error) {
	state, err := s.state(id)
	if err != nil {
		return Session{}, err
	}
	state.mu.Lock()
	defer state.mu.Unlock()
	return cloneSession(state.session), nil
}

func (s *Store) List(includeArchived bool) []Session {
	return s.Filter(ListFilter{IncludeArchived: includeArchived})
}

// ListFilter selects sessions by their caller-supplied source metadata.
// Non-nil fields are exact matches. A session without source metadata never
// matches a source filter, including a filter for an empty string.
type ListFilter struct {
	IncludeArchived  bool
	SourceApp        *string
	SourceInstanceID *string
	SourceExternalID *string
}

// Filter returns matching sessions, most recently updated first.
func (s *Store) Filter(filter ListFilter) []Session {
	s.mu.RLock()
	states := make([]*sessionState, 0, len(s.sessions))
	for _, state := range s.sessions {
		states = append(states, state)
	}
	s.mu.RUnlock()

	values := make([]Session, 0, len(states))
	for _, state := range states {
		state.mu.Lock()
		value := cloneSession(state.session)
		state.mu.Unlock()
		if !filter.IncludeArchived && value.State == StateArchived {
			continue
		}
		if !matchesSource(value.Source, filter) {
			continue
		}
		values = append(values, value)
	}
	sort.Slice(values, func(i, j int) bool {
		return values[i].UpdatedAt.After(values[j].UpdatedAt)
	})
	return values
}

func matchesSource(source *Source, filter ListFilter) bool {
	if filter.SourceApp == nil && filter.SourceInstanceID == nil && filter.SourceExternalID == nil {
		return true
	}
	if source == nil {
		return false
	}
	return (filter.SourceApp == nil || source.App == *filter.SourceApp) &&
		(filter.SourceInstanceID == nil || source.InstanceID == *filter.SourceInstanceID) &&
		(filter.SourceExternalID == nil || source.ExternalID == *filter.SourceExternalID)
}

func (s *Store) Append(id, eventType, turnID string, data []byte) (Event, error) {
	state, err := s.state(id)
	if err != nil {
		return Event{}, err
	}
	state.mu.Lock()
	if state.session.State == StateArchived {
		state.mu.Unlock()
		return Event{}, ErrArchived
	}
	event, err := s.appendLocked(state, id, eventType, turnID, data)
	state.mu.Unlock()
	if err != nil {
		return Event{}, err
	}
	s.publish(event)
	return event, nil
}

// appendLocked appends an event while the caller holds state.mu.
func (s *Store) appendLocked(state *sessionState, id, eventType, turnID string, data []byte) (Event, error) {
	event := Event{
		ID:        state.session.LastEventID + 1,
		Time:      time.Now().UTC(),
		Type:      eventType,
		SessionID: id,
		TurnID:    turnID,
		Data:      append(json.RawMessage(nil), data...),
	}
	if last, mergedData, ok := mergeableDeltaEvent(state, event); ok {
		merged, done, err := s.mergeDeltaLocked(state, last, mergedData, event)
		if done || err != nil {
			return merged, err
		}
		// The durable tail no longer matched the in-memory event, so the
		// merge was skipped; fall through to the plain append path.
	}
	encoded, err := json.Marshal(event)
	if err != nil {
		return Event{}, err
	}
	projected := cloneSession(state.session)
	if err := applyEvent(&projected, event); err != nil {
		return Event{}, fmt.Errorf("project event: %w", err)
	}
	encoded = append(encoded, '\n')
	if err := appendDurable(s.eventsPath(id), encoded); err != nil {
		return Event{}, err
	}
	state.session = projected
	state.events = append(state.events, event)
	if err := writeJSONAtomic(s.snapshotPath(id), state.session); err != nil {
		return Event{}, fmt.Errorf("write session snapshot: %w", err)
	}
	return event, nil
}

// mergeableDeltaEvent reports whether event is a streaming text delta that
// continues the session's last durable event. Consecutive assistant or
// reasoning deltas of one provider message are pure text fragments, so they
// fold into the preceding event: the log keeps one event per message
// instead of one per fragment, which shrinks the durable log and speeds up
// history loads. Merging requires the same type, turn, and an identical
// payload shape (every key except text equal, including the provider
// method) so no provider-specific field is ever dropped. It returns the
// last event plus its payload with the merged text.
//
// Merging stops once the accumulated payload reaches
// maxMergedDeltaEventBytes: each merge rewrites the tail line, so the cap
// bounds the rewrite cost of one event and keeps merged events well below
// the scanner limits of history and stream readers.
func mergeableDeltaEvent(state *sessionState, event Event) (Event, map[string]any, bool) {
	if event.Type != "message.assistant.delta" && event.Type != "message.reasoning.delta" {
		return Event{}, nil, false
	}
	if len(state.events) == 0 {
		return Event{}, nil, false
	}
	last := state.events[len(state.events)-1]
	if last.Type != event.Type || last.TurnID != event.TurnID {
		return Event{}, nil, false
	}
	if len(last.Data) >= maxMergedDeltaEventBytes {
		return Event{}, nil, false
	}
	var lastData, eventData map[string]any
	if err := json.Unmarshal(last.Data, &lastData); err != nil {
		return Event{}, nil, false
	}
	if err := json.Unmarshal(event.Data, &eventData); err != nil {
		return Event{}, nil, false
	}
	if len(lastData) != len(eventData) {
		return Event{}, nil, false
	}
	lastText, ok := lastData["text"].(string)
	if !ok {
		return Event{}, nil, false
	}
	eventText, ok := eventData["text"].(string)
	if !ok {
		return Event{}, nil, false
	}
	for key, value := range eventData {
		if key == "text" {
			continue
		}
		other, present := lastData[key]
		if !present || !reflect.DeepEqual(other, value) {
			return Event{}, nil, false
		}
	}
	lastData["text"] = lastText + eventText
	return last, lastData, true
}

// mergeDeltaLocked folds a delta event into the session's last durable event
// while the caller holds state.mu. The merged event keeps its original id, so
// the log stays contiguous and REST cursors are unaffected; the event time
// moves to the newest fragment so session UpdatedAt keeps tracking provider
// activity. Live subscribers receive the updated event again as a
// replacement for the id they already have.
//
// done reports whether the durable log was updated. When the on-disk tail no
// longer matches the in-memory event, done is false and the caller falls
// back to a plain append; once the rewrite succeeded, done is true and any
// later error (projection, snapshot) is final, mirroring appendLocked.
func (s *Store) mergeDeltaLocked(state *sessionState, last Event, mergedData map[string]any, event Event) (merged Event, done bool, err error) {
	data, err := json.Marshal(mergedData)
	if err != nil {
		return Event{}, false, err
	}
	merged = last
	merged.Time = event.Time
	merged.Data = data
	encoded, err := json.Marshal(merged)
	if err != nil {
		return Event{}, false, err
	}
	oldEncoded, err := json.Marshal(last)
	if err != nil {
		return Event{}, false, err
	}
	if err := rewriteLastEventLine(s.eventsPath(last.SessionID), append(oldEncoded, '\n'), append(encoded, '\n')); err != nil {
		return Event{}, false, nil
	}
	projected := cloneSession(state.session)
	if err := applyEvent(&projected, merged); err != nil {
		return Event{}, true, fmt.Errorf("project event: %w", err)
	}
	state.session = projected
	state.events[len(state.events)-1] = merged
	if err := writeJSONAtomic(s.snapshotPath(last.SessionID), state.session); err != nil {
		return Event{}, true, fmt.Errorf("write session snapshot: %w", err)
	}
	return merged, true, nil
}

// rewriteLastEventLine replaces the final line of the event log with the
// merged encoding of the same event. The file tail must match oldLine byte
// for byte before anything is written; any mismatch or I/O failure returns
// an error with the log left untouched so the caller can fall back to a
// plain append. A crash between the write and the sync can tear the tail
// line; the next Open repairs it by dropping that trailing event, which is
// safe here because only transient streaming deltas are ever rewritten.
func rewriteLastEventLine(path string, oldLine, newLine []byte) error {
	file, err := os.OpenFile(path, os.O_RDWR, 0o600)
	if err != nil {
		return err
	}
	stat, err := file.Stat()
	if err != nil {
		_ = file.Close()
		return err
	}
	if stat.Size() < int64(len(oldLine)) {
		_ = file.Close()
		return errors.New("event log shorter than the last event line")
	}
	offset := stat.Size() - int64(len(oldLine))
	tail := make([]byte, len(oldLine))
	if _, err := file.ReadAt(tail, offset); err != nil {
		_ = file.Close()
		return err
	}
	if !bytes.Equal(tail, oldLine) {
		_ = file.Close()
		return errors.New("event log tail does not match the last event")
	}
	if _, err := file.WriteAt(newLine, offset); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Truncate(offset + int64(len(newLine))); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Sync(); err != nil {
		_ = file.Close()
		return err
	}
	return file.Close()
}

// Archive moves a session's whole directory from the active store into
// Archive/<id>. Archiving appends a durable session.archived event first
// and then renames the directory; if the daemon stops between the two, the
// next Open completes the move, so the physical location always converges
// with the event log.
//
// Only strictly stopped sessions without active work can be archived;
// otherwise
// ErrSessionActive is returned and nothing changes. Archiving is
// idempotent: repeating it on a fully archived session succeeds, and
// repeating it after a failed move retries the move. If the move itself
// fails, the session stays archived in the index but its directory remains
// in the active area with all data intact, and a later retry or restart
// completes the move.
func (s *Store) Archive(id string) (Session, error) {
	if !validSessionID(id) {
		return Session{}, fmt.Errorf("%w: %q", ErrInvalidID, id)
	}
	state, err := s.state(id)
	if err != nil {
		return Session{}, err
	}
	state.mu.Lock()
	if state.session.State != StateArchived {
		if state.session.State != StateStopped {
			state.mu.Unlock()
			return Session{}, fmt.Errorf("%w: state %q is not stopped", ErrSessionActive, state.session.State)
		}
		if state.session.CurrentTurnID != "" || len(state.session.PendingApprovalIDs) > 0 {
			state.mu.Unlock()
			return Session{}, fmt.Errorf("%w: open turn or pending approval", ErrSessionActive)
		}
		event, err := s.appendLocked(state, id, "session.archived", "", nil)
		state.mu.Unlock()
		if err != nil {
			return Session{}, err
		}
		s.publish(event)
	} else {
		state.mu.Unlock()
	}
	if err := s.moveToArchive(id, state); err != nil {
		return Session{}, err
	}
	return s.Get(id)
}

// moveToArchive renames the session directory into Archive/. It is a no-op
// when the directory is already there.
func (s *Store) moveToArchive(id string, state *sessionState) error {
	state.mu.Lock()
	defer state.mu.Unlock()
	if state.archived {
		return nil
	}
	target := filepath.Join(s.archiveRoot(), id)
	if _, err := os.Stat(target); err == nil {
		return fmt.Errorf("%w: %s", ErrArchiveConflict, target)
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("check archive target: %w", err)
	}
	if err := os.MkdirAll(s.archiveRoot(), 0o700); err != nil {
		return fmt.Errorf("create session archive: %w", err)
	}
	if err := os.Rename(s.sessionDir(id), target); err != nil {
		return fmt.Errorf("move session to archive: %w", err)
	}
	state.archived = true
	syncDir(s.archiveRoot())
	syncDir(s.root)
	return nil
}

func (s *Store) EventsAfter(id string, after int64, limit int) ([]Event, error) {
	page, err := s.EventsPage(id, after, limit)
	return page.Events, err
}

// EventsPage returns events after an exclusive durable cursor plus enough
// metadata for a caller to page to the head captured by this request.
func (s *Store) EventsPage(id string, after int64, limit int) (EventPage, error) {
	state, err := s.state(id)
	if err != nil {
		return EventPage{}, err
	}
	limit = normalizeEventLimit(limit)
	state.mu.Lock()
	defer state.mu.Unlock()
	latest := state.session.LastEventID
	if after > latest {
		return EventPage{After: after, Limit: limit, NextAfter: after, LatestCursor: latest},
			fmt.Errorf("%w: %d > %d", ErrEventCursorAhead, after, latest)
	}
	start := sort.Search(len(state.events), func(index int) bool {
		return state.events[index].ID > after
	})
	events := make([]Event, 0, min(limit, len(state.events)-start))
	for _, event := range state.events[start:] {
		events = append(events, cloneEvent(event))
		if len(events) == limit {
			break
		}
	}
	next := after
	if len(events) > 0 {
		next = events[len(events)-1].ID
	}
	return EventPage{
		Events:       events,
		After:        after,
		Limit:        limit,
		NextAfter:    next,
		HasMore:      next < latest,
		LatestCursor: latest,
	}, nil
}

// EventsThrough returns at most limit events after after, never crossing the
// supplied durable high-water mark.
func (s *Store) EventsThrough(id string, after, highWater int64, limit int) ([]Event, error) {
	state, err := s.state(id)
	if err != nil {
		return nil, err
	}
	limit = normalizeEventLimit(limit)
	state.mu.Lock()
	defer state.mu.Unlock()
	start := sort.Search(len(state.events), func(index int) bool {
		return state.events[index].ID > after
	})
	events := make([]Event, 0, min(limit, len(state.events)-start))
	for _, event := range state.events[start:] {
		if event.ID > highWater {
			break
		}
		events = append(events, cloneEvent(event))
		if len(events) == limit {
			break
		}
	}
	return events, nil
}

// Subscribe installs the live notification queue before capturing and
// returning the durable high-water mark. Replaying through that mark and
// then consuming Events removes the history/live subscription race.
func (s *Store) Subscribe(id string) (*Subscription, int64, error) {
	s.mu.Lock()
	state := s.sessions[id]
	if state == nil {
		s.mu.Unlock()
		return nil, 0, ErrNotFound
	}
	subscription := &Subscription{
		events:   make(chan Event, subscriptionBuffer),
		overflow: make(chan struct{}),
	}
	if s.subscribers[id] == nil {
		s.subscribers[id] = make(map[*Subscription]struct{})
	}
	s.subscribers[id][subscription] = struct{}{}
	state.mu.Lock()
	highWater := state.session.LastEventID
	state.mu.Unlock()
	s.mu.Unlock()
	subscription.cancel = func() {
		s.mu.Lock()
		if subscribers := s.subscribers[id]; subscribers != nil {
			delete(subscribers, subscription)
			if len(subscribers) == 0 {
				delete(s.subscribers, id)
			}
		}
		s.mu.Unlock()
	}
	return subscription, highWater, nil
}

func normalizeEventLimit(limit int) int {
	if limit <= 0 {
		return DefaultEventPageSize
	}
	if limit > MaxEventPageSize {
		return MaxEventPageSize
	}
	return limit
}

func (s *Store) loadSession(dir, id string) (*sessionState, error) {
	events, err := readEventsRepairTail(filepath.Join(dir, "events.jsonl"))
	if err != nil {
		return nil, err
	}
	if len(events) == 0 {
		return nil, errors.New("session has no events")
	}
	var projected Session
	for _, event := range events {
		if event.SessionID != id {
			return nil, fmt.Errorf("event %d belongs to %s", event.ID, event.SessionID)
		}
		if err := applyEvent(&projected, event); err != nil {
			return nil, fmt.Errorf("event %d: %w", event.ID, err)
		}
	}
	if err := writeJSONAtomic(filepath.Join(dir, "session.json"), projected); err != nil {
		return nil, err
	}
	return &sessionState{session: projected, events: events}, nil
}

func applyEvent(projected *Session, event Event) error {
	switch event.Type {
	case "session.created":
		// The created snapshot is the Session itself. Legacy records carry
		// agentId instead of agentName; the id is kept in the projection so
		// the runtime can resolve it through the recorded id → name mapping.
		var created struct {
			Session
			LegacyAgentID string `json:"agentId"`
		}
		if err := json.Unmarshal(event.Data, &created); err != nil {
			return err
		}
		*projected = created.Session
		if projected.AgentName == "" {
			projected.AgentName = created.LegacyAgentID
		}
	case "session.state":
		var data StateEventData
		if err := json.Unmarshal(event.Data, &data); err != nil {
			return err
		}
		projected.State = data.State
		if data.State == StateStopped {
			projected.StopReason = data.Reason
		} else {
			projected.StopReason = ""
		}
	case "session.provider":
		var data ProviderEventData
		if err := json.Unmarshal(event.Data, &data); err != nil {
			return err
		}
		projected.AgentName = data.ResolvedAgentName()
		projected.Provider = data.Provider
		projected.ProviderSessionID = data.ProviderSessionID
	case "session.agent":
		// Appended when a configured agent is renamed: sessions that
		// referenced the old name are re-pointed at the new one.
		var data AgentRenameEventData
		if err := json.Unmarshal(event.Data, &data); err != nil {
			return err
		}
		projected.AgentName = data.AgentName
	case "session.archived":
		projected.State = StateArchived
	case "turn.started":
		projected.CurrentTurnID = event.TurnID
		projected.State = StateBusy
	case EventTurnCompleted, EventTurnFailed, EventTurnCancelled:
		if projected.CurrentTurnID == event.TurnID {
			projected.CurrentTurnID = ""
		}
		if projected.State != StateStopping && projected.State != StateStopped && projected.State != StateArchived {
			if len(projected.PendingApprovalIDs) > 0 {
				projected.State = StateWaitingApproval
			} else {
				projected.State = StateReady
			}
		}
	case "approval.requested":
		var data ApprovalEventData
		if err := json.Unmarshal(event.Data, &data); err != nil {
			return err
		}
		projected.PendingApprovalIDs = appendUnique(projected.PendingApprovalIDs, data.ApprovalID)
		projected.State = StateWaitingApproval
	case "approval.resolved":
		var data ApprovalEventData
		if err := json.Unmarshal(event.Data, &data); err != nil {
			return err
		}
		projected.PendingApprovalIDs = removeString(projected.PendingApprovalIDs, data.ApprovalID)
		if len(projected.PendingApprovalIDs) == 0 &&
			projected.State != StateStopping && projected.State != StateStopped && projected.State != StateArchived {
			if projected.CurrentTurnID != "" {
				projected.State = StateBusy
			} else {
				projected.State = StateReady
			}
		}
	}
	projected.LastEventID = event.ID
	projected.UpdatedAt = event.Time
	return nil
}

// OpenProviderProcess returns the newest provider process group that has not
// subsequently reached a stopped state. Older logs simply return no process
// metadata and continue to replay normally.
func (s *Store) OpenProviderProcess(id string) (ProviderProcessEventData, bool, error) {
	state, err := s.state(id)
	if err != nil {
		return ProviderProcessEventData{}, false, err
	}
	state.mu.Lock()
	defer state.mu.Unlock()
	var process ProviderProcessEventData
	open := false
	for _, event := range state.events {
		switch event.Type {
		case "provider.process.started":
			if err := json.Unmarshal(event.Data, &process); err != nil {
				return ProviderProcessEventData{}, false, fmt.Errorf("event %d: %w", event.ID, err)
			}
			open = process.PID > 0 && process.ProcessGroupID > 0
		case "session.state":
			var data StateEventData
			if json.Unmarshal(event.Data, &data) == nil && data.State == StateStopped {
				open = false
			}
		}
	}
	return process, open, nil
}

func readEventsRepairTail(path string) ([]Event, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	if len(data) > 0 && data[len(data)-1] != '\n' {
		lastNewline := bytes.LastIndexByte(data, '\n')
		validLength := lastNewline + 1
		if validLength < 0 {
			validLength = 0
		}
		if err := os.Truncate(path, int64(validLength)); err != nil {
			return nil, fmt.Errorf("repair event log tail: %w", err)
		}
		data = data[:validLength]
	}
	var events []Event
	scanner := bufio.NewScanner(bytes.NewReader(data))
	scanner.Buffer(make([]byte, 64*1024), 8*1024*1024)
	var previousID int64
	for scanner.Scan() {
		var event Event
		if err := json.Unmarshal(scanner.Bytes(), &event); err != nil {
			return nil, fmt.Errorf("invalid event log record: %w", err)
		}
		if event.ID != previousID+1 {
			return nil, fmt.Errorf("non-contiguous event id: got %d after %d", event.ID, previousID)
		}
		previousID = event.ID
		events = append(events, event)
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return events, nil
}

func syncDir(path string) {
	file, err := os.Open(path)
	if err != nil {
		return
	}
	_ = file.Sync()
	_ = file.Close()
}

func appendDurable(path string, data []byte) error {
	file, err := os.OpenFile(path, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o600)
	if err != nil {
		return err
	}
	if _, err := file.Write(data); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Sync(); err != nil {
		_ = file.Close()
		return err
	}
	return file.Close()
}

func writeJSONAtomic(path string, value any) error {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	dir := filepath.Dir(path)
	temp, err := os.CreateTemp(dir, ".tmp-*")
	if err != nil {
		return err
	}
	tempPath := temp.Name()
	cleanup := func() {
		_ = temp.Close()
		_ = os.Remove(tempPath)
	}
	if err := temp.Chmod(0o600); err != nil {
		cleanup()
		return err
	}
	if _, err := temp.Write(data); err != nil {
		cleanup()
		return err
	}
	if err := temp.Sync(); err != nil {
		cleanup()
		return err
	}
	if err := temp.Close(); err != nil {
		_ = os.Remove(tempPath)
		return err
	}
	if err := os.Rename(tempPath, path); err != nil {
		_ = os.Remove(tempPath)
		return err
	}
	if dirFile, err := os.Open(dir); err == nil {
		_ = dirFile.Sync()
		_ = dirFile.Close()
	}
	return nil
}

func NewID(prefix string) (string, error) {
	random := make([]byte, 8)
	if _, err := rand.Read(random); err != nil {
		return "", err
	}
	return fmt.Sprintf("%s_%x%s", prefix, time.Now().UTC().UnixMilli(), hex.EncodeToString(random)), nil
}

func (s *Store) state(id string) (*sessionState, error) {
	s.mu.RLock()
	state := s.sessions[id]
	s.mu.RUnlock()
	if state == nil {
		return nil, ErrNotFound
	}
	return state, nil
}

func (s *Store) publish(event Event) {
	s.mu.Lock()
	defer s.mu.Unlock()
	for subscription := range s.subscribers[event.SessionID] {
		select {
		case subscription.events <- cloneEvent(event):
		default:
			delete(s.subscribers[event.SessionID], subscription)
			close(subscription.overflow)
		}
	}
	if len(s.subscribers[event.SessionID]) == 0 {
		delete(s.subscribers, event.SessionID)
	}
}

func (s *Store) removeSession(id string) {
	s.mu.Lock()
	delete(s.sessions, id)
	s.mu.Unlock()
}

func (s *Store) sessionDir(id string) string {
	return filepath.Join(s.root, id)
}

func (s *Store) snapshotPath(id string) string {
	return filepath.Join(s.sessionDir(id), "session.json")
}

func (s *Store) eventsPath(id string) string {
	return filepath.Join(s.sessionDir(id), "events.jsonl")
}

func cloneSession(value Session) Session {
	value.PendingApprovalIDs = append([]string(nil), value.PendingApprovalIDs...)
	value.Source = cloneSource(value.Source)
	value.LaunchEnvironment = cloneEnvironment(value.LaunchEnvironment)
	return value
}

func cloneEnvironment(value map[string]string) map[string]string {
	if value == nil {
		return nil
	}
	cloned := make(map[string]string, len(value))
	for key, entry := range value {
		cloned[key] = entry
	}
	return cloned
}

func cloneSource(value *Source) *Source {
	if value == nil {
		return nil
	}
	cloned := *value
	return &cloned
}

func cloneEvent(value Event) Event {
	value.Data = append(json.RawMessage(nil), value.Data...)
	return value
}

func appendUnique(values []string, value string) []string {
	for _, current := range values {
		if current == value {
			return values
		}
	}
	return append(values, value)
}

func removeString(values []string, value string) []string {
	result := values[:0]
	for _, current := range values {
		if current != value {
			result = append(result, current)
		}
	}
	return result
}
