package session

import (
	"bufio"
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"
)

var (
	ErrNotFound = errors.New("session not found")
	// ErrArchived rejects writes to an archived session. Archived sessions
	// are read-only: their directory has been moved under Archive/ and no
	// new events may be appended.
	ErrArchived = errors.New("session is archived")
	// ErrSessionActive rejects archiving a session that still has active
	// work: a running or starting provider, an open turn, or a pending
	// approval.
	ErrSessionActive = errors.New("session has active work and cannot be archived")
	// ErrInvalidID rejects session identifiers that are not safe store
	// directory names.
	ErrInvalidID = errors.New("invalid session id")
	// ErrArchiveConflict reports that the archive target already exists.
	ErrArchiveConflict = errors.New("archive target already exists")
)

// ArchiveDirName is the subdirectory of the session store that holds
// archived sessions. It never contains a live session and is never scanned
// as one.
const ArchiveDirName = "Archive"

var sessionIDPattern = regexp.MustCompile(`^ses_[a-z0-9]+$`)

// validSessionID reports whether id is a safe store directory name. Session
// IDs are generated by NewID, so anything else (path separators, dots,
// traversal attempts) is rejected.
func validSessionID(id string) bool {
	return sessionIDPattern.MatchString(id)
}

type sessionState struct {
	mu      sync.Mutex
	session Session
	events  []Event
	// archived reports whether the session directory lives under Archive/.
	// It is the in-memory record of the physical location, which is the
	// authoritative archive signal.
	archived bool
}

type Store struct {
	root string

	mu          sync.RWMutex
	sessions    map[string]*sessionState
	subscribers map[string]map[chan Event]struct{}
}

func Open(root string) (*Store, error) {
	if err := os.MkdirAll(root, 0o700); err != nil {
		return nil, fmt.Errorf("create session store: %w", err)
	}
	archiveRoot := filepath.Join(root, ArchiveDirName)
	if err := os.MkdirAll(archiveRoot, 0o700); err != nil {
		return nil, fmt.Errorf("create session archive: %w", err)
	}
	store := &Store{
		root:        root,
		sessions:    make(map[string]*sessionState),
		subscribers: make(map[string]map[chan Event]struct{}),
	}
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, fmt.Errorf("read session store: %w", err)
	}
	for _, entry := range entries {
		if !entry.IsDir() || !strings.HasPrefix(entry.Name(), "ses_") {
			// Archive itself and any unrelated entry are never sessions.
			continue
		}
		state, err := store.loadSession(filepath.Join(root, entry.Name()), entry.Name())
		if err != nil {
			return nil, fmt.Errorf("load %s: %w", entry.Name(), err)
		}
		if state.session.State == StateArchived {
			// The archived event was appended but the daemon stopped before
			// moving the directory. Complete the move so the physical
			// location matches the event log again.
			if err := os.Rename(filepath.Join(root, entry.Name()), filepath.Join(archiveRoot, entry.Name())); err == nil {
				state.archived = true
				syncDir(archiveRoot)
				syncDir(root)
			}
		}
		store.sessions[entry.Name()] = state
	}
	archivedEntries, err := os.ReadDir(archiveRoot)
	if err != nil {
		return nil, fmt.Errorf("read session archive: %w", err)
	}
	for _, entry := range archivedEntries {
		if !entry.IsDir() || !strings.HasPrefix(entry.Name(), "ses_") {
			continue
		}
		if existing, exists := store.sessions[entry.Name()]; exists {
			if existing.archived {
				// Moved here by the interrupted-archive recovery above.
				continue
			}
			return nil, fmt.Errorf("session %s exists in both the store and the archive", entry.Name())
		}
		state, err := store.loadSession(filepath.Join(archiveRoot, entry.Name()), entry.Name())
		if err != nil {
			return nil, fmt.Errorf("load archived %s: %w", entry.Name(), err)
		}
		// The physical location is authoritative: a session under Archive/
		// is archived even if its event log predates the archived event.
		state.session.State = StateArchived
		state.archived = true
		store.sessions[entry.Name()] = state
	}
	return store, nil
}

func (s *Store) Root() string {
	return s.root
}

// ArchiveRoot returns the directory that holds archived sessions.
func (s *Store) ArchiveRoot() string {
	return s.archiveRoot()
}

func (s *Store) archiveRoot() string {
	return filepath.Join(s.root, ArchiveDirName)
}

func (s *Store) Create(input CreateInput) (Session, error) {
	if err := ValidateLaunchEnvironment(input.LaunchEnvironment); err != nil {
		return Session{}, err
	}
	now := time.Now().UTC()
	id, err := NewID("ses")
	if err != nil {
		return Session{}, err
	}
	if input.Title == "" {
		input.Title = "New Session"
	}
	value := Session{
		ID:                id,
		Title:             input.Title,
		Cwd:               input.Cwd,
		AgentName:         input.AgentName,
		LaunchEnvironment: cloneEnvironment(input.LaunchEnvironment),
		State:             StateReady,
		CreatedAt:         now,
		UpdatedAt:         now,
	}
	state := &sessionState{session: value}
	dir := s.sessionDir(id)
	if err := os.Mkdir(dir, 0o700); err != nil {
		return Session{}, fmt.Errorf("create session directory: %w", err)
	}

	s.mu.Lock()
	s.sessions[id] = state
	s.mu.Unlock()

	data, err := json.Marshal(value)
	if err != nil {
		s.removeSession(id)
		_ = os.RemoveAll(dir)
		return Session{}, err
	}
	if _, err := s.Append(id, "session.created", "", data); err != nil {
		s.removeSession(id)
		_ = os.RemoveAll(dir)
		return Session{}, err
	}
	return s.Get(id)
}

func (s *Store) Get(id string) (Session, error) {
	state, err := s.state(id)
	if err != nil {
		return Session{}, err
	}
	state.mu.Lock()
	defer state.mu.Unlock()
	return cloneSession(state.session), nil
}

func (s *Store) List(includeArchived bool) []Session {
	s.mu.RLock()
	states := make([]*sessionState, 0, len(s.sessions))
	for _, state := range s.sessions {
		states = append(states, state)
	}
	s.mu.RUnlock()

	values := make([]Session, 0, len(states))
	for _, state := range states {
		state.mu.Lock()
		value := cloneSession(state.session)
		state.mu.Unlock()
		if !includeArchived && value.State == StateArchived {
			continue
		}
		values = append(values, value)
	}
	sort.Slice(values, func(i, j int) bool {
		return values[i].UpdatedAt.After(values[j].UpdatedAt)
	})
	return values
}

func (s *Store) Append(id, eventType, turnID string, data []byte) (Event, error) {
	state, err := s.state(id)
	if err != nil {
		return Event{}, err
	}
	state.mu.Lock()
	if state.session.State == StateArchived {
		state.mu.Unlock()
		return Event{}, ErrArchived
	}
	event, err := s.appendLocked(state, id, eventType, turnID, data)
	state.mu.Unlock()
	if err != nil {
		return Event{}, err
	}
	s.publish(event)
	return event, nil
}

// appendLocked appends an event while the caller holds state.mu.
func (s *Store) appendLocked(state *sessionState, id, eventType, turnID string, data []byte) (Event, error) {
	event := Event{
		ID:        state.session.LastEventID + 1,
		Time:      time.Now().UTC(),
		Type:      eventType,
		SessionID: id,
		TurnID:    turnID,
		Data:      append(json.RawMessage(nil), data...),
	}
	encoded, err := json.Marshal(event)
	if err != nil {
		return Event{}, err
	}
	encoded = append(encoded, '\n')
	if err := appendDurable(s.eventsPath(id), encoded); err != nil {
		return Event{}, err
	}
	if err := applyEvent(&state.session, event); err != nil {
		return Event{}, fmt.Errorf("project event: %w", err)
	}
	state.events = append(state.events, event)
	if err := writeJSONAtomic(s.snapshotPath(id), state.session); err != nil {
		return Event{}, fmt.Errorf("write session snapshot: %w", err)
	}
	return event, nil
}

// Archive moves a session's whole directory from the active store into
// Archive/<id>. Archiving appends a durable session.archived event first
// and then renames the directory; if the daemon stops between the two, the
// next Open completes the move, so the physical location always converges
// with the event log.
//
// Only sessions without active work can be archived (no starting/running
// provider state, no open turn, no pending approval); otherwise
// ErrSessionActive is returned and nothing changes. Archiving is
// idempotent: repeating it on a fully archived session succeeds, and
// repeating it after a failed move retries the move. If the move itself
// fails, the session stays archived in the index but its directory remains
// in the active area with all data intact, and a later retry or restart
// completes the move.
func (s *Store) Archive(id string) (Session, error) {
	if !validSessionID(id) {
		return Session{}, fmt.Errorf("%w: %q", ErrInvalidID, id)
	}
	state, err := s.state(id)
	if err != nil {
		return Session{}, err
	}
	state.mu.Lock()
	if state.session.State != StateArchived {
		switch state.session.State {
		case StateStarting, StateBusy, StateWaitingApproval:
			state.mu.Unlock()
			return Session{}, fmt.Errorf("%w: state %q", ErrSessionActive, state.session.State)
		}
		if state.session.CurrentTurnID != "" || len(state.session.PendingApprovalIDs) > 0 {
			state.mu.Unlock()
			return Session{}, fmt.Errorf("%w: open turn or pending approval", ErrSessionActive)
		}
		event, err := s.appendLocked(state, id, "session.archived", "", nil)
		state.mu.Unlock()
		if err != nil {
			return Session{}, err
		}
		s.publish(event)
	} else {
		state.mu.Unlock()
	}
	if err := s.moveToArchive(id, state); err != nil {
		return Session{}, err
	}
	return s.Get(id)
}

// moveToArchive renames the session directory into Archive/. It is a no-op
// when the directory is already there.
func (s *Store) moveToArchive(id string, state *sessionState) error {
	state.mu.Lock()
	defer state.mu.Unlock()
	if state.archived {
		return nil
	}
	target := filepath.Join(s.archiveRoot(), id)
	if _, err := os.Stat(target); err == nil {
		return fmt.Errorf("%w: %s", ErrArchiveConflict, target)
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("check archive target: %w", err)
	}
	if err := os.MkdirAll(s.archiveRoot(), 0o700); err != nil {
		return fmt.Errorf("create session archive: %w", err)
	}
	if err := os.Rename(s.sessionDir(id), target); err != nil {
		return fmt.Errorf("move session to archive: %w", err)
	}
	state.archived = true
	syncDir(s.archiveRoot())
	syncDir(s.root)
	return nil
}

func (s *Store) EventsAfter(id string, after int64, limit int) ([]Event, error) {
	state, err := s.state(id)
	if err != nil {
		return nil, err
	}
	if limit <= 0 || limit > 1000 {
		limit = 500
	}
	state.mu.Lock()
	defer state.mu.Unlock()
	events := make([]Event, 0, min(limit, len(state.events)))
	for _, event := range state.events {
		if event.ID <= after {
			continue
		}
		events = append(events, cloneEvent(event))
		if len(events) == limit {
			break
		}
	}
	return events, nil
}

func (s *Store) Subscribe(id string) (<-chan Event, func(), error) {
	if _, err := s.state(id); err != nil {
		return nil, nil, err
	}
	ch := make(chan Event, 256)
	s.mu.Lock()
	if s.subscribers[id] == nil {
		s.subscribers[id] = make(map[chan Event]struct{})
	}
	s.subscribers[id][ch] = struct{}{}
	s.mu.Unlock()
	cancel := func() {
		s.mu.Lock()
		if subscribers := s.subscribers[id]; subscribers != nil {
			if _, ok := subscribers[ch]; ok {
				delete(subscribers, ch)
			}
			if len(subscribers) == 0 {
				delete(s.subscribers, id)
			}
		}
		s.mu.Unlock()
	}
	return ch, cancel, nil
}

func (s *Store) loadSession(dir, id string) (*sessionState, error) {
	events, err := readEventsRepairTail(filepath.Join(dir, "events.jsonl"))
	if err != nil {
		return nil, err
	}
	if len(events) == 0 {
		return nil, errors.New("session has no events")
	}
	var projected Session
	for _, event := range events {
		if event.SessionID != id {
			return nil, fmt.Errorf("event %d belongs to %s", event.ID, event.SessionID)
		}
		if err := applyEvent(&projected, event); err != nil {
			return nil, fmt.Errorf("event %d: %w", event.ID, err)
		}
	}
	if err := writeJSONAtomic(filepath.Join(dir, "session.json"), projected); err != nil {
		return nil, err
	}
	return &sessionState{session: projected, events: events}, nil
}

func applyEvent(projected *Session, event Event) error {
	switch event.Type {
	case "session.created":
		// The created snapshot is the Session itself. Legacy records carry
		// agentId instead of agentName; the id is kept in the projection so
		// the runtime can resolve it through the recorded id → name mapping.
		var created struct {
			Session
			LegacyAgentID string `json:"agentId"`
		}
		if err := json.Unmarshal(event.Data, &created); err != nil {
			return err
		}
		*projected = created.Session
		if projected.AgentName == "" {
			projected.AgentName = created.LegacyAgentID
		}
	case "session.state":
		var data StateEventData
		if err := json.Unmarshal(event.Data, &data); err != nil {
			return err
		}
		projected.State = data.State
	case "session.provider":
		var data ProviderEventData
		if err := json.Unmarshal(event.Data, &data); err != nil {
			return err
		}
		projected.AgentName = data.ResolvedAgentName()
		projected.Provider = data.Provider
		projected.ProviderSessionID = data.ProviderSessionID
	case "session.agent":
		// Appended when a configured agent is renamed: sessions that
		// referenced the old name are re-pointed at the new one.
		var data AgentRenameEventData
		if err := json.Unmarshal(event.Data, &data); err != nil {
			return err
		}
		projected.AgentName = data.AgentName
	case "session.archived":
		projected.State = StateArchived
	case "turn.started":
		projected.CurrentTurnID = event.TurnID
		projected.State = StateBusy
	case "turn.completed", "turn.failed", "turn.cancelled":
		if projected.CurrentTurnID == event.TurnID {
			projected.CurrentTurnID = ""
		}
		if projected.State != StateStopped && projected.State != StateArchived {
			projected.State = StateReady
		}
	case "approval.requested":
		var data ApprovalEventData
		if err := json.Unmarshal(event.Data, &data); err != nil {
			return err
		}
		projected.PendingApprovalIDs = appendUnique(projected.PendingApprovalIDs, data.ApprovalID)
		projected.State = StateWaitingApproval
	case "approval.resolved":
		var data ApprovalEventData
		if err := json.Unmarshal(event.Data, &data); err != nil {
			return err
		}
		projected.PendingApprovalIDs = removeString(projected.PendingApprovalIDs, data.ApprovalID)
		if len(projected.PendingApprovalIDs) == 0 {
			if projected.CurrentTurnID != "" {
				projected.State = StateBusy
			} else {
				projected.State = StateReady
			}
		}
	}
	projected.LastEventID = event.ID
	projected.UpdatedAt = event.Time
	return nil
}

func readEventsRepairTail(path string) ([]Event, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	if len(data) > 0 && data[len(data)-1] != '\n' {
		lastNewline := bytes.LastIndexByte(data, '\n')
		validLength := lastNewline + 1
		if validLength < 0 {
			validLength = 0
		}
		if err := os.Truncate(path, int64(validLength)); err != nil {
			return nil, fmt.Errorf("repair event log tail: %w", err)
		}
		data = data[:validLength]
	}
	var events []Event
	scanner := bufio.NewScanner(bytes.NewReader(data))
	scanner.Buffer(make([]byte, 64*1024), 8*1024*1024)
	var previousID int64
	for scanner.Scan() {
		var event Event
		if err := json.Unmarshal(scanner.Bytes(), &event); err != nil {
			return nil, fmt.Errorf("invalid event log record: %w", err)
		}
		if event.ID != previousID+1 {
			return nil, fmt.Errorf("non-contiguous event id: got %d after %d", event.ID, previousID)
		}
		previousID = event.ID
		events = append(events, event)
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return events, nil
}

func syncDir(path string) {
	file, err := os.Open(path)
	if err != nil {
		return
	}
	_ = file.Sync()
	_ = file.Close()
}

func appendDurable(path string, data []byte) error {
	file, err := os.OpenFile(path, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o600)
	if err != nil {
		return err
	}
	if _, err := file.Write(data); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Sync(); err != nil {
		_ = file.Close()
		return err
	}
	return file.Close()
}

func writeJSONAtomic(path string, value any) error {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	dir := filepath.Dir(path)
	temp, err := os.CreateTemp(dir, ".tmp-*")
	if err != nil {
		return err
	}
	tempPath := temp.Name()
	cleanup := func() {
		_ = temp.Close()
		_ = os.Remove(tempPath)
	}
	if err := temp.Chmod(0o600); err != nil {
		cleanup()
		return err
	}
	if _, err := temp.Write(data); err != nil {
		cleanup()
		return err
	}
	if err := temp.Sync(); err != nil {
		cleanup()
		return err
	}
	if err := temp.Close(); err != nil {
		_ = os.Remove(tempPath)
		return err
	}
	if err := os.Rename(tempPath, path); err != nil {
		_ = os.Remove(tempPath)
		return err
	}
	if dirFile, err := os.Open(dir); err == nil {
		_ = dirFile.Sync()
		_ = dirFile.Close()
	}
	return nil
}

func NewID(prefix string) (string, error) {
	random := make([]byte, 8)
	if _, err := rand.Read(random); err != nil {
		return "", err
	}
	return fmt.Sprintf("%s_%x%s", prefix, time.Now().UTC().UnixMilli(), hex.EncodeToString(random)), nil
}

func (s *Store) state(id string) (*sessionState, error) {
	s.mu.RLock()
	state := s.sessions[id]
	s.mu.RUnlock()
	if state == nil {
		return nil, ErrNotFound
	}
	return state, nil
}

func (s *Store) publish(event Event) {
	s.mu.Lock()
	defer s.mu.Unlock()
	for ch := range s.subscribers[event.SessionID] {
		select {
		case ch <- cloneEvent(event):
		default:
			delete(s.subscribers[event.SessionID], ch)
			close(ch)
		}
	}
	if len(s.subscribers[event.SessionID]) == 0 {
		delete(s.subscribers, event.SessionID)
	}
}

func (s *Store) removeSession(id string) {
	s.mu.Lock()
	delete(s.sessions, id)
	s.mu.Unlock()
}

func (s *Store) sessionDir(id string) string {
	return filepath.Join(s.root, id)
}

func (s *Store) snapshotPath(id string) string {
	return filepath.Join(s.sessionDir(id), "session.json")
}

func (s *Store) eventsPath(id string) string {
	return filepath.Join(s.sessionDir(id), "events.jsonl")
}

func cloneSession(value Session) Session {
	value.PendingApprovalIDs = append([]string(nil), value.PendingApprovalIDs...)
	value.LaunchEnvironment = cloneEnvironment(value.LaunchEnvironment)
	return value
}

func cloneEnvironment(value map[string]string) map[string]string {
	if value == nil {
		return nil
	}
	cloned := make(map[string]string, len(value))
	for key, entry := range value {
		cloned[key] = entry
	}
	return cloned
}

func cloneEvent(value Event) Event {
	value.Data = append(json.RawMessage(nil), value.Data...)
	return value
}

func appendUnique(values []string, value string) []string {
	for _, current := range values {
		if current == value {
			return values
		}
	}
	return append(values, value)
}

func removeString(values []string, value string) []string {
	result := values[:0]
	for _, current := range values {
		if current != value {
			result = append(result, current)
		}
	}
	return result
}
