package session

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"
)

const (
	StateStarting        = "starting"
	StateReady           = "ready"
	StateBusy            = "busy"
	StateWaitingApproval = "waiting_approval"
	StateStopping        = "stopping"
	StateStopped         = "stopped"
	StateArchived        = "archived"
)

const (
	StopReasonRequested      = "requested"
	StopReasonCompleted      = "completed"
	StopReasonProviderError  = "provider_error"
	StopReasonStartupError   = "startup_error"
	StopReasonDaemonRecovery = "daemon_recovery"
)

const (
	EventTurnCompleted = "turn.completed"
	EventTurnFailed    = "turn.failed"
	EventTurnCancelled = "turn.cancelled"
	EventMessageInput  = "message.input"
)

// MessageRole describes message provenance only. It is not an authorization
// level, a trust boundary, or a provider instruction-priority signal.
type MessageRole string

const (
	MessageRoleUser      MessageRole = "user"
	MessageRoleSystem    MessageRole = "system"
	MessageRoleAgent     MessageRole = "agent"
	MessageRoleAssistant MessageRole = "assistant"
)

// MessageSender identifies the source of an inbound message. AgentHub stores
// these fields as caller-provided provenance and does not authenticate them.
type MessageSender struct {
	ID        string `json:"id,omitempty"`
	Name      string `json:"name,omitempty"`
	SessionID string `json:"sessionId,omitempty"`
}

// MessageInput is the canonical durable input event payload. MessageID,
// ReplyTo, and CorrelationID are reserved compatibility fields for future
// agent-to-agent correlation; this task does not route or deliver them.
type MessageInput struct {
	Text          string         `json:"text"`
	Role          MessageRole    `json:"role"`
	Sender        *MessageSender `json:"sender,omitempty"`
	Steer         bool           `json:"steer"`
	MessageID     string         `json:"messageId,omitempty"`
	ReplyTo       string         `json:"replyTo,omitempty"`
	CorrelationID string         `json:"correlationId,omitempty"`
}

// MessageInputError is returned when an inbound message cannot be accepted.
// Code and Field are suitable for mapping to the public API error envelope.
type MessageInputError struct {
	Code    string
	Field   string
	Message string
}

func (e *MessageInputError) Error() string {
	return e.Message
}

// NormalizeMessageInput applies the stable inbound compatibility rules:
// omitted role means user, assistant is provider-output-only, and sender
// identity fields are trimmed and validated without being authenticated.
func NormalizeMessageInput(value MessageInput) (MessageInput, error) {
	value.Role = MessageRole(strings.ToLower(strings.TrimSpace(string(value.Role))))
	if value.Role == "" {
		value.Role = MessageRoleUser
	}
	switch value.Role {
	case MessageRoleUser, MessageRoleSystem, MessageRoleAgent:
	case MessageRoleAssistant:
		return MessageInput{}, &MessageInputError{
			Code: "assistant_message_forbidden", Field: "role",
			Message: "role assistant is reserved for output generated by the current session provider",
		}
	default:
		return MessageInput{}, &MessageInputError{
			Code: "invalid_message_role", Field: "role",
			Message: fmt.Sprintf("unsupported message role %q; expected user, system, or agent", value.Role),
		}
	}
	if strings.TrimSpace(value.Text) == "" {
		return MessageInput{}, &MessageInputError{
			Code: "invalid_message_text", Field: "text", Message: "message text is required",
		}
	}
	if value.Sender != nil {
		sender := *value.Sender
		sender.ID = strings.TrimSpace(sender.ID)
		sender.Name = strings.TrimSpace(sender.Name)
		sender.SessionID = strings.TrimSpace(sender.SessionID)
		if sender.ID == "" && sender.Name == "" && sender.SessionID == "" {
			return MessageInput{}, &MessageInputError{
				Code: "invalid_message_sender", Field: "sender",
				Message: "sender must contain at least one of id, name, or sessionId",
			}
		}
		for _, field := range []struct {
			name  string
			value string
		}{
			{name: "sender.id", value: sender.ID},
			{name: "sender.name", value: sender.Name},
			{name: "sender.sessionId", value: sender.SessionID},
		} {
			entry := field.value
			if strings.ContainsRune(entry, '\x00') {
				return MessageInput{}, &MessageInputError{
					Code: "invalid_message_sender", Field: field.name,
					Message: fmt.Sprintf("%s must not contain NUL", field.name),
				}
			}
			if len(entry) > 4096 {
				return MessageInput{}, &MessageInputError{
					Code: "invalid_message_sender", Field: field.name,
					Message: fmt.Sprintf("%s is too long", field.name),
				}
			}
		}
		value.Sender = &sender
	}
	for _, field := range []struct {
		name  string
		value string
	}{
		{name: "messageId", value: value.MessageID},
		{name: "replyTo", value: value.ReplyTo},
		{name: "correlationId", value: value.CorrelationID},
	} {
		entry := field.value
		if strings.ContainsRune(entry, '\x00') {
			return MessageInput{}, &MessageInputError{
				Code: "invalid_message_reference", Field: field.name,
				Message: fmt.Sprintf("%s must not contain NUL", field.name),
			}
		}
		if len(entry) > 4096 {
			return MessageInput{}, &MessageInputError{
				Code: "invalid_message_reference", Field: field.name,
				Message: fmt.Sprintf("%s is too long", field.name),
			}
		}
	}
	value.MessageID = strings.TrimSpace(value.MessageID)
	value.ReplyTo = strings.TrimSpace(value.ReplyTo)
	value.CorrelationID = strings.TrimSpace(value.CorrelationID)
	return value, nil
}

// TurnTerminalEventData is the provider-independent payload of a canonical
// turn terminal event. A successful completion has an empty payload. Failed
// and cancelled turns may carry a human-readable error or stable reason.
// Provider-native completion payloads remain available on their preceding
// diagnostic event and are never copied into this public payload.
type TurnTerminalEventData struct {
	Error  string `json:"error,omitempty"`
	Reason string `json:"reason,omitempty"`
}

type Session struct {
	ID                 string            `json:"id"`
	Title              string            `json:"title"`
	Cwd                string            `json:"cwd"`
	AgentName          string            `json:"agentName,omitempty"`
	IdempotencyKey     string            `json:"idempotencyKey,omitempty"`
	Source             *Source           `json:"source,omitempty"`
	LaunchEnvironment  map[string]string `json:"launchEnvironment,omitempty"`
	Provider           string            `json:"provider,omitempty"`
	InputCapabilities  InputCapabilities `json:"inputCapabilities"`
	ProviderSessionID  string            `json:"providerSessionId,omitempty"`
	State              string            `json:"state"`
	StopReason         string            `json:"stopReason,omitempty"`
	CurrentTurnID      string            `json:"currentTurnId,omitempty"`
	PendingApprovalIDs []string          `json:"pendingApprovalIds,omitempty"`
	LastEventID        int64             `json:"lastEventId"`
	CreatedAt          time.Time         `json:"createdAt"`
	UpdatedAt          time.Time         `json:"updatedAt"`
}

// Source is caller-supplied metadata for correlating sessions with the
// application that created them. AgentHub stores these values verbatim and
// does not authenticate them or impose uniqueness.
type Source struct {
	App        string            `json:"app,omitempty"`
	InstanceID string            `json:"instanceId,omitempty"`
	ExternalID string            `json:"externalId,omitempty"`
	Metadata   map[string]string `json:"metadata,omitempty"`
}

// InputCapabilities describes provider-independent input behavior for this
// Session. It is captured with the Session so archived Sessions remain
// self-describing even when the daemon configuration later changes.
type InputCapabilities struct {
	Steer bool `json:"steer"`
}

// Event is a durable canonical session event. StartTime is populated for a
// delta event folded with at least one following fragment; it preserves the
// first fragment timestamp while Time continues to track the newest fragment.
type Event struct {
	ID        int64           `json:"id"`
	Time      time.Time       `json:"time"`
	StartTime *time.Time      `json:"startTime,omitempty"`
	Type      string          `json:"type"`
	SessionID string          `json:"sessionId"`
	TurnID    string          `json:"turnId,omitempty"`
	Data      json.RawMessage `json:"data,omitempty"`
}

// EventPage is a stable snapshot page of a session's durable event log.
// After and NextAfter use exclusive cursor semantics: a subsequent request
// passes NextAfter as its After value. Before and NextBefore are the
// backward counterpart, populated only by backward pages (EventsPageBefore):
// a subsequent backward request passes NextBefore as its Before value. They
// are zero on forward pages and omitted from their JSON encoding.
type EventPage struct {
	Events        []Event `json:"events"`
	After         int64   `json:"after"`
	Limit         int     `json:"limit"`
	NextAfter     int64   `json:"nextAfter"`
	HasMore       bool    `json:"hasMore"`
	Before        int64   `json:"before,omitempty"`
	NextBefore    int64   `json:"nextBefore,omitempty"`
	HasMoreBefore bool    `json:"hasMoreBefore,omitempty"`
	LatestCursor  int64   `json:"latestCursor"`
}

type CreateInput struct {
	Title             string
	Cwd               string
	AgentName         string
	IdempotencyKey    string
	Source            *Source
	LaunchEnvironment map[string]string
	Provider          string
	InputCapabilities InputCapabilities
}

// TurnSummary is a rebuildable index entry over the durable event log. Every
// reference is a stable event ID; no filesystem path or byte offset escapes
// through the public API.
type TurnSummary struct {
	ID                string         `json:"id"`
	Status            string         `json:"status"`
	StartedAt         time.Time      `json:"startedAt"`
	CompletedAt       *time.Time     `json:"completedAt,omitempty"`
	FirstEventID      int64          `json:"firstEventId"`
	LastEventID       int64          `json:"lastEventId"`
	TriggerEventID    int64          `json:"triggerEventId,omitempty"`
	FinalReplyEventID int64          `json:"finalReplyEventId,omitempty"`
	TriggerPreview    string         `json:"triggerPreview,omitempty"`
	TriggerRole       MessageRole    `json:"triggerRole,omitempty"`
	TriggerSender     *MessageSender `json:"triggerSender,omitempty"`
	FinalReplyPreview string         `json:"finalReplyPreview,omitempty"`
	EventCount        int            `json:"eventCount"`
	ToolEventCount    int            `json:"toolEventCount"`
}

// TurnPage uses exclusive stable event-ID cursors in both directions. A
// Turn's FirstEventID is its cursor key.
type TurnPage struct {
	Turns         []TurnSummary `json:"turns"`
	After         int64         `json:"after"`
	Before        int64         `json:"before,omitempty"`
	Limit         int           `json:"limit"`
	NextAfter     int64         `json:"nextAfter"`
	NextBefore    int64         `json:"nextBefore,omitempty"`
	HasMore       bool          `json:"hasMore"`
	HasMoreBefore bool          `json:"hasMoreBefore,omitempty"`
	LatestCursor  int64         `json:"latestCursor"`
}

// ValidateLaunchEnvironment checks values before they are persisted and
// passed to an operating-system process. Environment variable names cannot
// be empty or contain '=' or NUL, and values cannot contain NUL.
func ValidateLaunchEnvironment(environment map[string]string) error {
	for key, value := range environment {
		if key == "" {
			return errors.New("environment variable name cannot be empty")
		}
		if strings.ContainsAny(key, "=\x00") {
			return fmt.Errorf("invalid environment variable name %q", key)
		}
		if strings.ContainsRune(value, '\x00') {
			return fmt.Errorf("environment variable %q contains NUL", key)
		}
	}
	return nil
}

type StateEventData struct {
	State  string `json:"state"`
	Reason string `json:"reason,omitempty"`
}

// ProviderProcessEventData is durable evidence that an adapter started an OS
// process group. It lets a replacement daemon terminate and confirm the old
// group after an ungraceful daemon exit before publishing stopped.
type ProviderProcessEventData struct {
	PID            int `json:"pid"`
	ProcessGroupID int `json:"processGroupId"`
}

type ApprovalEventData struct {
	ApprovalID string `json:"approvalId"`
}

// AgentRenameEventData is the payload of the session.agent event, appended
// when a configured agent is renamed so the session follows the new name.
type AgentRenameEventData struct {
	AgentName string `json:"agentName"`
}

// LaunchEnvironmentEventData is the payload of the
// session.launch-environment event. It carries the session's full effective
// launch environment after an overlay was merged, so replay replaces the
// projected map with the payload verbatim instead of re-applying the
// overlay. The historical session.created snapshot is never rewritten.
type LaunchEnvironmentEventData struct {
	Environment map[string]string `json:"environment"`
}

// ProviderEventData is the payload of the session.provider event. AgentName
// names the agent configuration the session runs with.
type ProviderEventData struct {
	AgentName         string            `json:"agentName,omitempty"`
	Provider          string            `json:"provider"`
	ProviderSessionID string            `json:"providerSessionId,omitempty"`
	InputCapabilities InputCapabilities `json:"inputCapabilities"`
}
